language: python
sudo: false
python:
  - "3.6"
services:
  - docker
install:
  - pip install -r requirements.dev.txt
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Style"
      name: "Style"
      script:
        - find agent -name \*.py -exec flake8 {} +
    - stage: "Tests"
      name: "Tests"
      script:
        - pytest -v --cov=agent
    - stage: "Build"
      name: "Docker"
      script:
        - docker build -t test
